version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: bakery-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bakery
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bakery-rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./bakery-backend
      dockerfile: Dockerfile
    container_name: bakery-backend
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bakery?schema=public
      PORT: 3001
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"
    volumes:
      - ./bakery-backend:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bakery-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: "http://localhost:3001/api"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Worker Service (for processing orders)
  worker:
    build:
      context: ./bakery-backend
      dockerfile: Dockerfile
    container_name: bakery-worker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bakery?schema=public
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./bakery-backend:/app
      - /app/node_modules
    command: >
      sh -c "node src/workers/orderProcessor.js"
    healthcheck:
      test: ["CMD", "pgrep", "node"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  rabbitmq-data:
